from typing import Any

import pandas  # Imports the csv data

from pandas import DataFrame
import matplotlib.pyplot as plt
import numpy as np
import seaborn

print(__name__)


# "healthcare-dataset-stroke-data.csv"

class StrokeAnalysis:
    def __init__(self, path: str):
        self._path = path  # Path pointing to the csv file to be analyzed
        self._healthcare_dataset = pandas.read_csv(path)
        self._healthcare_array = self._healthcare_dataset.to_numpy()

    def logical_analysis(self):
        print("Performing logical analysis")

        discarding = pandas.isna(self._healthcare_dataset["bmi"])
        # Comienzo del analisis logico

        self.bmi_incomplete = discarding.to_numpy()
        self.stroked_patients = (self._healthcare_array[:, -1] == 1)
        self.diseased_patients = (self._healthcare_array[:, 4] == 1)
        self.n_stroked_patients = sum(self.stroked_patients)
        self.n_non_stroked_patients = sum(~self.stroked_patients)
        self.males = (self._healthcare_array[:, 1] == "Male") | (
                self._healthcare_array[:, 1] == "Other")  # Considered Other as males
        self.females = self._healthcare_array[:, 1] == "Female"
        self.smokers = (self._healthcare_array[:, 10] == 'smokes') | (
                self._healthcare_array[:, 10] == 'formerly smoked')
        self.stroked_smokers = (self.smokers) & (self.stroked_patients)

    def age_glucose_study(self):
        self.stroked_ages = self._healthcare_array[self.stroked_patients, 2]
        self.stroked_smokers_ages = self._healthcare_array[self.stroked_smokers, 2]
        self.ages = self._healthcare_array[:, 2]

    def formating(self):
        """This function formats data for a quantitative analysis. Mean = 0 std deviation = 1 for each feature.
        It also provides the stroke (output) info in the last column"""

        selected_atributes_name = ['Gender', 'Age', 'hypertension', 'heart disease', 'glucose level', 'Stroke']
        # print(f' The attributes to be analyzed are {selected_atributes_name}')
        selected_atributes = [2, 3, 4, 8, 9, -1]
        simplified_health_array = self._healthcare_array[~self.bmi_incomplete, :]
        simplified_health_array = simplified_health_array[:, selected_atributes]
        feature_means = np.mean(simplified_health_array, axis=0)
        centered_simplified_array = simplified_health_array - feature_means
        feature_deviation = np.std(centered_simplified_array.astype(float), axis=0)

        self.standarized_array = centered_simplified_array / feature_deviation



    def PCA_and_LDA_analysis(self):
        print("Performing PCA and LDA analysis")
        self.complete_correlation_matrix = np.cov(self.standarized_array.astype(float).T)
        self.PCA_LDA_correlation_matrix =  np.cov(self.standarized_array[:,:-1].astype(float).T)
        print('Performed covariance matrix')

        # Computing and sorting eigenvectors and eigenvalues of the covariance matrix
        values, vectors = np.linalg.eig(self.PCA_LDA_correlation_matrix)
        eig_order = np.argsort(-values)

        self.sorted_values = values[eig_order]
        self.sorted_vectors = vectors[:,eig_order]

        # Dataset in the base generated by the eigen analysis
        eigen_dataset = np.matmul(self.standarized_array[:,:-1],self.sorted_vectors)

        # Nearest centroid classifier applied to the eigen dataset array

        stroked_patients_NCC = self.standarized_array[:, -1] > 0 # Remember that the dataset has been normalized.
        print(sum(stroked_patients_NCC))
        stroked_eigen_mean = np.mean(eigen_dataset[stroked_patients_NCC,:-1], axis = 0 )[:,None]
        non_stroked_eigen_mean = np.mean(eigen_dataset[~stroked_patients_NCC,:-1], axis = 0 )[:,None]

        function_weights = non_stroked_eigen_mean - stroked_eigen_mean
        function_beta = 0.5 * np.matmul(non_stroked_eigen_mean.T, non_stroked_eigen_mean) - 0.5 * np.matmul(stroked_eigen_mean.T, stroked_eigen_mean)

        # We now proceed to classify the patients with respect to the LDA method (PCA + NCC)


        self.stroked_classification = np.matmul(eigen_dataset[stroked_patients_NCC,:-1], function_weights) - function_beta
        self.non_stroked_classification = np.matmul(eigen_dataset[~stroked_patients_NCC,:-1], function_weights) - function_beta

        self.stroke_prediction_success = sum(self.stroked_classification < 0)/ len(self.stroked_classification)
        self.non_stroke_prediction_success = sum(self.non_stroked_classification > 0)/len(self.non_stroked_classification)




if __name__ == '__main__':
    print(__name__)
    d = StrokeAnalysis("healthcare-dataset-stroke-data.csv")
    d.logical_analysis()
    print(f'This is a functioning test, N of stroked patients: {d.n_stroked_patients}')
    d.formating()
    d.PCA_and_LDA_analysis()



    # print(d.PCA_LDA_correlation_matrix)
    # print(sum(d.bmi_incomplete[d.stroked_patients]))

